
export default {
  SELECT_FOTO:                        'SELECT_FOTO',
  PRODCUT_TO_CART:                    'PRODCUT_TO_CART',
  ERASE_PRODUCT:                      'ERASE_PRODUCT',
  CHANGE_QTTY:                        'CHANGE_QTTY',
  CREACIONES_RECEIVED:                'CREACIONES_RECEIVED',
  FERIAS_RECEIVED:                    'FERIAS_RECEIVED',
  CONTENIDOS_RECEIVED:                'CONTENIDOS_RECEIVED',
  ENLACES_RECEIVED:                   'ENLACES_RECEIVED',
  MOVETO_FERIA_SECTION:               'MOVETO_FERIA_SECTION',
  MOVETO_CREACION_SECTION:            'MOVETO_CREACION_SECTION',
  SHOW_NOTIFICATION:                  'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION:                  'HIDE_NOTIFICATION',
  TOGGLE_MODAL:                       'TOGGLE_MODAL',
  USER_CREATED:                       'USER_CREATED',
  USERS_RECEIVED:                     'USERS_RECEIVED',
  ADD_USER_INFO:                      'ADD_USER_INFO',
  CURRENT_USER_RECEIVED:              'CURRENT_USER_RECEIVED',
  CURRENT_USER_TO_DB:                 'CURRENT_USER_TO_DB',
  CAMBIAR_CURRENT_USER_MODIFICABLE:   'CAMBIAR_CURRENT_USER_MODIFICABLE',
  PASSWORD_CHANGED:                   'PASSWORD_CHANGED',
  NAV_ACTIVE:                         'NAV_ACTIVE',
  LOAD_CARRO:                         'LOAD_CARRO',
  RESEND_EMAIL:                       'RESEND_EMAIL',
  GUARDAR_DATOS_PEDIDO:               'GUARDAR_DATOS_PEDIDO',
  MARKER_CLICKED:                     'MARKER_CLICKED',
  TOGGLE_YEAR:                        'TOGGLE_YEAR',
  ELEMENTO_VENDIDO:                   'ELEMENTO_VENDIDO',
  MOVE_CAROUSELL:                     'MOVE_CAROUSELL',
  LOAD_FROM_INSTAGRAM:                'LOAD_FROM_INSTAGRAM',
  CHANGE_SCREEN_WIDTH:                'CHANGE_SCREEN_WIDTH',
  FIX_NAVBAR:                         'FIX_NAVBAR',
}
