
export default {
  SELECT_FOTO:              'SELECT_FOTO',
  PRODCUT_TO_CART:          'PRODCUT_TO_CART',
  ERASE_PRODUCT:            'ERASE_PRODUCT',
  CHANGE_QTTY:              'CHANGE_QTTY',
  CREACIONES_RECEIVED:      'CREACIONES_RECEIVED',
  FERIAS_RECEIVED:          'FERIAS_RECEIVED',
  CONTENIDOS_RECEIVED:      'CONTENIDOS_RECEIVED',
  ENLACES_RECEIVED:         'ENLACES_RECEIVED',
  MOVETO_FERIA_SECTION:     'MOVETO_FERIA_SECTION',
  MOVETO_CREACION_SECTION:  'MOVETO_CREACION_SECTION',
  SHOW_NOTIFICATION:        'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION:        'HIDE_NOTIFICATION',
  TOGGLE_MODAL:               'TOGGLE_MODAL',
}
